#define PARAMETER_DELAY_LEFT 0
#define PARAMETER_DELAY_RIGHT 1
#define PARAMETER_PITCH_RATE 2
#define PARAMETER_PITCH_AMOUNT 3
#define PARAMETER_FEEDBACK 4

#define PARAMETER_AMPLITUDE_RATE 5
#define PARAMETER_AMPLITUDE_AMOUNT 6

#define PARAMETER_HIGH_PASS 7
#define PARAMETER_LOW_PASS 8

#define PARAMETER_WIDTH 9
#define PARAMETER_WET_DRY 10

#define PARAMETER_GAIN_MASTER 11

#define L 0
#define R 1
