#define PARAMETER_DELAY_LEFT 0
#define PARAMETER_DELAY_RIGHT 1
#define PARAMETER_PITCH_RATE_LEFT 2
#define PARAMETER_PITCH_RATE_RIGHT 3
#define PARAMETER_PITCH_AMOUNT_LEFT 4
#define PARAMETER_PITCH_AMOUNT_RIGHT 5
#define PARAMETER_FEEDBACK_LEFT 6
#define PARAMETER_FEEDBACK_RIGHT 7


#define PARAMETER_AMPLITUDE_RATE 8
#define PARAMETER_AMPLITUDE_AMOUNT 9

#define PARAMETER_HIGH_PASS 10
#define PARAMETER_LOW_PASS 11

#define PARAMETER_WIDTH 12
#define PARAMETER_WET_DRY 13

#define PARAMETER_GAIN_MASTER 14

#define L 0
#define R 1
