#define PARAMETER_DELAY 0
#define PARAMETER_PITCH_RATE 1
#define PARAMETER_PITCH_AMOUNT 2
#define PARAMETER_FEEDBACK 3

#define PARAMETER_AMPLITUDE_RATE 4
#define PARAMETER_AMPLITUDE_AMOUNT 5

#define PARAMETER_HIGH_PASS 6
#define PARAMETER_LOW_PASS 7

#define PARAMETER_WIDTH 8
#define PARAMETER_WET_DRY 9

#define PARAMETER_GAIN_MASTER 10
